### ISSUE TITLE
Had to set STATIC_PRECOMPILER_OUTPUT_DIR = '' to work on django 1.11.2

### ISSUE THREAD

**Issue by boosh** [andreyfedoseev/django-static-precompiler#103]
I just installed this with libsass on OSX. I could see my scss files were being written to `static/COMPILED/sass/site.css`, but django couldn't find them. The URL in the page was `/static/sass/site.css` but it seems the static file finder couldn't translate this to the file in the `COMPILED` directory.

Setting `STATIC_PRECOMPILER_OUTPUT_DIR = ''` fixed the issue.

Here's my config:
```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'static_precompiler.finders.StaticPrecompilerFinder',
)

STATIC_PRECOMPILER_COMPILERS = (
    ('static_precompiler.compilers.libsass.SCSS', {
        "sourcemap_enabled": True,
        "precision": 8,
    }),
    ('static_precompiler.compilers.libsass.SASS', {
        "sourcemap_enabled": True,
        "precision": 8,
    }),
)

# STATIC_PRECOMPILER_OUTPUT_DIR = ''
```
Usage in `layout.html`:
```
{% load compile_static %}
{% load static %}
...
<link rel="stylesheet" type="text/css" href="{% static "/sass/site.scss"|compile %}" />
```
The above outputs as:
```
<link rel="stylesheet" type="text/css" href="/static/sass/site.css" />
```
But this file can't be found without overriding `STATIC_PRECOMPILER_OUTPUT_DIR`.

**Comment by sir-sigurd** [comment]
You should try to use relative path:
`{% static "/sass/site.scss"|compile %}` -> `{% static "sass/site.scss"|compile %}`.

**Comment by boosh** [comment]
Yeah relative paths fixes it. Thanks.
