### ISSUE TITLE
Cannot run compiler in Travis build.

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [andreyfedoseev/django-static-precompiler#119]
Hi,

Any chance you tried to compile scss when doing a Travis CI build?
When I run it with:
`python manage.py compilestatic --settings=<my_proj>.test_settings`
The build sticks and throws an error:
`FileNotFoundError: [Errno 2] No such file or directory: 'sass': 'sass'`
The same command works absolutely fine on local virtual environment and when using tox locally.

**Comment by andreyfedoseev** [comment]
It seems you don't have SASS installed in your Travis environment. If it is installed, make sure you specify correct path to `sass` executable (see http://django-static-precompiler.readthedocs.io/en/stable/compiler-settings.html#sass-scss)

**Comment by Tomasz-Kluczkowski** [comment]
Thx a lot Andrey!

That was it.
gem install sass did it.
I was falsely thinking that your package does not require sass preinstalled :).

Do you think it would be a good idea for me to create a docs pull request with a small note added to how to use section reminding new users (like me) that a preinstalled sass is required for django-static-precompiler to work?

Take care,

Tomasz

On 18 Jun 2018, at 05:43, Andrey Fedoseev <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems you don't have SASS installed in your Travis environment. If it is installed, make sure you specify correct path to sass executable (see http://django-static-precompiler.readthedocs.io/en/stable/compiler-settings.html#sass-scss<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdjango-static-precompiler.readthedocs.io%2Fen%2Fstable%2Fcompiler-settings.html%23sass-scss&data=02%7C01%7C%7C0ef2f212812a41f482c608d5d4d60625%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636648938039939870&sdata=DbXkzSe4YkA2DXtvaBZjIv1Sw%2BaES5PSmMmdXQ4%2B2L8%3D&reserved=0>)

**Comment by andreyfedoseev** [comment]
> Do you think it would be a good idea for me to create a docs pull request with a small note added to how to use section reminding new users (like me) that a preinstalled sass is required for django-static-precompiler to work?

Yes, I think it's good idea if it would allow to avoid such confusion in the future. Note that SASS isn't the only transpiler supported by django-static-precompiler, so if you want to update the documentation make sure to mention other transpilers as well.
