### ISSUE TITLE
Wierd StaticCompilationError caused by django-static-precompiler

### ISSUE THREAD

**Issue by cddumanov** [andreyfedoseev/django-static-precompiler#120]
On project we use django-static-precompiler and scss. When I ran localy got this weird error that points to nothing literally. No info at internet or references at docs. I thought it connected to sass packecge but it already installed at my system.

![image](https://user-images.githubusercontent.com/43003794/45479762-07be9f80-b750-11e8-899b-709721894125.png)
![image](https://user-images.githubusercontent.com/43003794/45479773-0db48080-b750-11e8-8340-a18994cffd46.png)
OR
![image](https://user-images.githubusercontent.com/43003794/45479791-1a38d900-b750-11e8-8388-cf869268f912.png)

**Comment by andreyfedoseev** [comment]
Hi @cddumanov 

Could you compile that file using `sass` command line tool and see if it works? Like `sass /path/to/your/file.scss`

**Comment by cddumanov** [comment]
@andreyfedoseev Hello. I do.

**Comment by cddumanov** [comment]
`> /home/artem/Projects/python/carbondelta/.venv/lib/python3.6/site-packages/static_precompiler/compilers/scss.py(84)compile_file()
-> return_code, out, errors = utils.run_command(args, None, cwd=cwd)
(Pdb) args
self = <static_precompiler.compilers.scss.SCSS object at 0x7f3d3691c9b0>
source_path = 'css/factsheet.scss'
(Pdb) cwd
'/home/artem/Projects/python/carbondelta/website/static'
(Pdb) n
> /home/artem/Projects/python/carbondelta/.venv/lib/python3.6/site-packages/static_precompiler/compilers/scss.py(86)compile_file()
-> if return_code:
(Pdb) return_code
64
(Pdb) out
'Could not find an option named "sourcemap".\n\nUsage: sass <input.scss> [output.css]\n       sass <input.scss>:<output.css> <input/>:<output/>\n\n━━━ Input and Output ━━━━━━━━━━━━━━━━━━━\n    --[no-]stdin               Read the stylesheet from stdin.\n    --[no-]indented            Use the indented syntax for input from stdin.\n-I, --load-path=<PATH>         A path to use when resolving imports.\n                               May be passed multiple times.\n\n-s, --style=<NAME>             Output style.\n                               [expanded (default), compressed]\n\n    --update                   Only compile out-of-date stylesheets.\n\n━━━ Source Maps ━━━━━━━━━━━━━━━━━━━━━━━━\n    --[no-]source-map          Whether to generate source maps.\n                               (defaults to on)\n\n    --source-map-urls          How to link from source maps to source files.\n                               [relative (default), absolute]\n\n    --[no-]embed-sources       Embed source file contents in source maps.\n    --[no-]embed-source-map    Embed source map contents in CSS.\n\n━━━ Other ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n    --watch                    Watch stylesheets and recompile when they change.\n    --[no-]poll                Manually check for changes rather than using a native watcher.\n                               Only valid with --watch.\n\n    --[no-]stop-on-error       Don\'t compile more files once an error is encountered.\n-i, --interactive              Run an interactive SassScript shell.\n-c, --[no-]color               Whether to emit terminal colors.\n-q, --[no-]quiet               Don\'t print warnings.\n    --[no-]trace               Print full Dart stack traces for exceptions.\n-h, --help                     Print this usage information.\n    --version                  Print the version of Dart Sass.\n'
(Pdb) `

**Comment by andreyfedoseev** [comment]
It seems that you're using DartSass which has a different set of command line options compared to the original SASS implementation (Ruby Sass). You can either switch to Ruby SASS, or make a custom compiler that would work with DartSass. In the latter case you can send a pull request to include this new compiler to `static_precompiler`. You can also try it without the `sourcemap` option.

**Comment by Tomasz-Kluczkowski** [comment]
Yes I can confirm that DartSass does not work with django-static-precompiler. I had to switch back to ruby sass.

**Comment by anhphamduy** [comment]
@andreyfedoseev I've had the same problem. 

Seems like they are making Ruby Sass [deprecated](https://sass-lang.com/ruby-sass). Have you got any updates on this?
