### ISSUE TITLE
Unable to install django-static-precompiler using poetry

### ISSUE THREAD

**Issue by oliverandrich** [andreyfedoseev/django-static-precompiler#123]
I opened an issue in the Poetry project, which was closed because of understandable reasons. 

https://github.com/sdispater/poetry/issues/1551

Maybe you want to have a look at it. Somehow in the context of poetry, the package behaves like it is installed with python 2. And the hints for environment markers sounds reasonable to me.

**Comment by andreyfedoseev** [comment]
I updated `setup.py` to remove the dynamic dependencies, I hope this resolves the issue.
