### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by mszeflinski** [andreyfedoseev/django-static-precompiler#124]
Hello.
Django dropped support for Python 2 in version 2.0 and now with version 3.0 it drops support also for Python 3 compatibility APIs.
**django.utils.six** is no longer available in Django 3.0. This project should switch to six library or drop compatibility layer as well.

**Comment by Igoranze** [comment]
Is this issue soon going to be committed to master?

**Comment by BarnabasSzabolcs** [comment]
That PR has to be fixed so that it keeps compatibility with django 2.

**Comment by BarnabasSzabolcs** [comment]
@Igoranze now, the Django 3.0 and 3.1 compatibility is there, if the PR gets merged. Until then, you can use
`-e git://github.com/BarnabasSzabolcs/django-static-precompiler.git#egg=django-static-precompiler` in your requirements.txt file.

**Comment by andreyfedoseev** [comment]
Support for Django 3.0 and 3.1 has been added in version 2.0 which I just released.
