### ISSUE TITLE
SCSS variables fail to emit inside CSS calc

### ISSUE THREAD

**Issue by b9chris** [andreyfedoseev/django-static-precompiler#140]
```
body {
  $test: 10px;
  left: calc(100% - $test);
}
```

Should emit:

```
body {
  left: calc(100% - 10px);
}
```

Instead emits:

```
body {
  left: calc(100% - $test);
}
```

**Comment by andreyfedoseev** [comment]
@b9chris 

Can you confirm that your snippet works correctly if you compile with with SCSS, without using `django-static-precompiler`?

Also, what is `calc()` exactly? My guess is that SCSS doesn't recognize this function and doesn't apply variable substitution.

It tried it with the following snippet and it worked:

```
body {
  $test: 10px;
  left: 100px - $test;
}
```

The output is:

```
body {
  left: 90px;
}
```
