### ISSUE TITLE
LESS Prod environment Show CSS instead of less

### ISSUE THREAD

**Issue by InhamiRei** [andreyfedoseev/django-static-precompiler#147]
prod environment i set
`
STATIC_PRECOMPILER_COMPILERS = (
    ('static_precompiler.compilers.LESS', {
        "sourcemap_enabled": True,
    }),
)
`
![image](https://user-images.githubusercontent.com/53500845/167379233-dfd597c1-4cd7-4fb2-979f-9da4ddbad8f4.png)
Show CSS instead of less
But
development environment
No matter what I set "sourcemap_enabled": True or False
Show only
![image](https://user-images.githubusercontent.com/53500845/167379324-27c53ec7-c263-4cc8-9c53-f914476df39f.png)

**Comment by andreyfedoseev** [comment]
I don't quite understand what is the issue. Please elaborate on what result you expect and what you're getting instead.
