### ISSUE TITLE
Support for Handlebars' precompiler

### ISSUE THREAD

**Issue by Matt3o12** [andreyfedoseev/django-static-precompiler#38]
Handlebars allows me to define HTML templates and write clearer coffee script code (because I don't need to add all this HTML into my code).  
Handlebars has a precompiled which increases the load time significantly and reduces the size of the package. 

Adding support for the precompiler would save me and probably some other users some time. 

More information about precompiling can be found on [Handlebars' homepage](http://handlebarsjs.com/precompilation.html).

**Comment by KevinSeghetti** [comment]
I second this request

**Comment by andreyfedoseev** [comment]
Handlebars compiler was added in 1.1

**Comment by KevinSeghetti** [comment]
awesome. I also see babel source map, the other feature I needed, Thanks
