### ISSUE TITLE
Full verbosity does not show which files are compiled

### ISSUE THREAD

**Issue by webmaster128** [andreyfedoseev/django-static-precompiler#53]
I am having massive trouble with `./manage.py compilestatic` and `./manage.py compilestatic --watch` because change detection seems buggy and I don't understand which files are re-compiled after changes.

I think that the verbosity setting in `compilestatic` should output much more information.

The information which source file is compiled to which output file should be already existing in `verbosity=2` and `verbosity=3` should add information about skipped files as well.

Thanks for your effort!

**Comment by andreyfedoseev** [comment]
Fixed in d25761a2a7322360aaf44d50ef795cc118ad544e
