### ISSUE TITLE
Was missing CONTEXT_URL for templates.

### ISSUE THREAD

**Issue by basicdays** [andreyfedoseev/django-static-precompiler#55]
Hey all,

I'm relatively new to Django, so I haven't used any versions older than 1.8 yet. I noticed your documentation referenced that I would be able to output the `CONTEXT_URL` setting from my templates. I noticed however that variable was always coming up blank in my templates. I found I had to add `django.template.context_processors.static` to my `context_processors` in my settings.py in order to have access to `CONTEXT_URL`. Not sure if that may require a documentation change or I just missed something. Otherwise everything so far seems to be working!

**Comment by basicdays** [comment]
Here's some refs to django's documentation too:

* https://docs.djangoproject.com/en/1.8/ref/templates/api/#django-template-context-processors-static
* https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/

**Comment by andreyfedoseev** [comment]
I think you actually mean `STATIC_URL` variable. If so, then you should enable `django.template.context_processors.static` context processor to have this variable available in template context. However, this isn't related to `django-static-precompiler`, it's a feature of Django itself.

You can add `STATIC_PRECOMPILER_PREPEND_STATIC_URL=True` to settings. In that case the `{% compile %}` template tag (which is part of `django-static-precompiler`) will add `STATIC_URL` to the URLs of compiled files), so you don't have to add it yourself. Note that `STATIC_URL` is added *only* to the output of `{% compile %}` tag.

**Comment by basicdays** [comment]
Ah yes, I had meant to write `STATIC_URL` and not `CONTEXT_URL`. I only mention this as the readme uses the `CONTEXT_URL` in the template examples without referencing that additional context_processor would have been needed.
