### ISSUE TITLE
Cannot Specify Include Directories

### ISSUE THREAD

**Issue by timolson** [andreyfedoseev/django-static-precompiler#56]
Our SASS file imports 3rd-party scss files from a directory outside our project, and there is no way to specify an include directory for the SASS compiler.  Same problem as #52 (no way to change command-line arguments)

**Comment by andreyfedoseev** [comment]
What command line argument do you want to use for that?

**Comment by timolson** [comment]
We use multiple `--load-path` arguments to import 3rd-party components which are not part of our core project.

**Comment by andreyfedoseev** [comment]
Support for `load-path` option was added in 1.1
