### ISSUE TITLE
StaticPrecompilerFinder not working for me

### ISSUE THREAD

**Issue by scottix** [andreyfedoseev/django-static-precompiler#63]
I am using the template tag to compile a less file and it is creating the directory COMPILED and everything there seems to work.

```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'static_precompiler',
)
```

```
{% static 'less/styles.less'|compile %}
```

When I try to go to the page it cannot find the corresponding file.
I do have the finder specified
```
STATICFILES_FINDER = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'static_precompiler.finders.StaticPrecompilerFinder',
)
```

I do findstatic on other static files on my site and they show up but the COMPILED directory doesn't.

```
python manage.py findstatic fi/css/styles.css
Found 'fi/css/styles.css'
```
```
python manage.py findstatic COMPILED/less/styles.css
No matching file found for 'COMPILED/less/styles.css'.
```

**Comment by andreyfedoseev** [comment]
@scottix Is the file actually compiled? Can you locate it in `COMPILED/less`?

**Comment by scottix** [comment]
Yes it is actually there.

**Comment by sedrubal** [comment]
same here...

**Comment by andreyfedoseev** [comment]
Well, guys, after spending quite a while trying to reproduce the problem I found that you have a typo in your settings. It's `STATICFILES_FINDERS`, not `STATICFILES_FINDER`
