### ISSUE TITLE
general support for command line options

### ISSUE THREAD

**Issue by jaheba** [andreyfedoseev/django-static-precompiler#64]
It may be a good idea to generally allow to pass command line options to the compilers. (See #56 and #61).

For example:

```
STATIC_PRECOMPILER_COMPILERS = (
    ('static_precompiler.compilers.Babel', {"executable": "/usr/bin/babel", options=["--modules", "amd"]}),
)
```

However some options may causes conflicts and cause the precompiler to malfunction. I think it should be made clear in the documentation that these option should be only used at one's own risk.

**Comment by andreyfedoseev** [comment]
> However some options may causes conflicts and cause the precompiler to malfunction.

That's the reason why I don't allow to use arbitrary command line options. The options are passed to `subprocess.Popen` and may cause all kinds of unexpected behavour if used incorrectly. I'm trying to keep everything foolproof.

Although, I add the compiler options by user request.

**Comment by timolson** [comment]
I see this is closed, but with no checkins?  What is the status here?  Our project currently requires multiple `--load-path` arguments passed to `scss` in order to find 3rd-party components used by our project.  We are unable to use `django-static-precompiler` and hacked our own solution instead. (see #56)

**Comment by jaheba** [comment]
Disallowing arbitrary options is intentional.

However it is fairly easy to add specific behavior. Each option in ``settings.py`` is passed to the compiler:

```python
def __init__(self,
executable=settings.SCSS_EXECUTABLE,
    compass_enabled=settings.SCSS_USE_COMPASS,
    my_new_fancy_option=None):
```
Then just apply this option in ``compile_source`` (and lately also ``compile_file``) by adding it to the ``args`` list which is passed to ``subprocess.Popen``.

I believe @andreyfedoseev would be happy to accept a pull request supporting ``-load-path``.

**Comment by andreyfedoseev** [comment]
> I believe @andreyfedoseev would be happy to accept a pull request supporting -load-path.

Yes, and I'm going to include the support for `--load-path` into 1.1 release plan.

**Comment by jaheba** [comment]
@andreyfedoseev Just to be sure: You don't plan to implement it yourself but would add the feature if implemented to the next release?

**Comment by andreyfedoseev** [comment]
> Just to be sure: You don't plan to implement it yourself

I do plan to implement it myself, except for the case if someone sends a pull request beforehand.
