### ISSUE TITLE
__init__() got an unexpected keyword argument 'sourcemap_enabled'

### ISSUE THREAD

**Issue by soulraven** [andreyfedoseev/django-static-precompiler#71]
i get this error and i don't know why, http://dpaste.com/0HTNSG7

# Settings for static precompilers for css files
STATIC_PRECOMPILER_OUTPUT_DIR = 'compiled'
STATIC_PRECOMPILER_MTIME_DELAY = 1

STATIC_PRECOMPILER_COMPILERS = (
	('static_precompiler.compilers.LESS', {"sourcemap_enabled": True, "executable": "/usr/bin/lessc"}),
)

**Comment by sir-sigurd** [comment]
Can you post traceback here, please? Your link doesn't work anymore.

**Comment by andreyfedoseev** [comment]
Support for source maps was added in 1.1.
