### ISSUE TITLE
Babel get error: unknown option `--modules'

### ISSUE THREAD

**Issue by qas612820704** [andreyfedoseev/django-static-precompiler#74]
Hello, this is my setting.py

```py
# myapp/setting.py
STATIC_PRECOMPILER_COMPILERS = (
 # ...
  ('static_precompiler.compilers.Babel',{'modules':"transform-es2015-classes,transform-react-jsx"}),
  # ...
)
```

I don't know why I get this error 

I use this with the wrong way?

**Comment by qas612820704** [comment]
It seems like lastest version of `babel(6.1.2)`
change options `--modules` to `--plugins`
After chage I solve the problems

**Comment by andreyfedoseev** [comment]
Support for `plugins` option was added in 1.1
