### ISSUE TITLE
Add an option to specify output style in SCSS/SASS/libsass

### ISSUE THREAD

**Issue by philipbelesky** [andreyfedoseev/django-static-precompiler#78]
With apologies if this is already possible (I had a look through but couldn't find anything that hinted at it). 

I could take a stab at implementing this if you'd like — I assume I'd just be checking for the option and adding then appending ```--output-style=nested``` to the ```args``` as is done with ```sourcemap_enabled``` and the like.

**Comment by andreyfedoseev** [comment]
Fixed in bbeba4ee891bd9cd2db24b2db0b90b6889176a73
