### ISSUE TITLE
Handle included files

### ISSUE THREAD

**Issue by mpauly** [andreyfedoseev/django-static-precompiler#79]
Hey,
I got the following problem using django static precompiler; I have a bunch of .less files that are all included in a single styles.less. This styles.less is being compiled and served to the user.
Now on one hand the other less files do not compile individually as they depend on each other. On the  other hand in development I rarely change the main file and normally only touch the included files. However I am unsure how to handle this scenario with static precompiler. In my case styles.less is only compiled if a change is directly applied to styles.less itself, but not when one of the included files is changed, which would be what I want. 
Two other possible solutions for me would either be to recompile every file once a single file in the watched directory has changed, e.g. if I change include1.less all files are recompiled or to intrdoduce a switch that fully disables caching. Then the file would be regenerated at every request which probably for development should be okay as well.
The last thing should be fairly easy to implement however I am not sure whether there is a better solution. Any help on this would be appreciated. 
I opened an issue for this as I wasn't able to find any information on this particular question and I believe this is something that might come up for other people as well.
Thanks for all the great work on static precomiler!

**Comment by andreyfedoseev** [comment]
django-static-precompiler is designed to detect changes in imported file and re-compile the main file if necessary. At the moment its implemented for LESS, SCSS, Stylus compilers. This feature is supposed to "just work". If for some reason it doesn't work for you, please file a bug report.

**Comment by mpauly** [comment]
Hey,
before that didn't work for me. I assume that was, because the included files weren't stored in the 'static' dir. I now moved them to the static dir, and it is working as expected. So just for future reference: As long as the included files are in the static dir as well, automatic compilation also works for included files. 
Thanks for your help!
