### ISSUE TITLE
Output on stderr is always considered an error

### ISSUE THREAD

**Issue by invliD** [andreyfedoseev/django-static-precompiler#83]
The sass compiler can output messages like:

    DEPRECATION WARNING:
    Sass 3.5 will no longer support Ruby 1.9.3.
    Please upgrade to Ruby 2.0.0 or greater as soon as possible.

This message is not fatal, and in fact sass still returns the status code 0, but since django-static-precompiler considers any output on stderr an error, the compilation fails anyway.

**Comment by andreyfedoseev** [comment]
This is fixed in 1.4, it's available on PyPI.
