### ISSUE TITLE
Doubled directory name in path?

### ISSUE THREAD

**Issue by YozhEzhi** [andreyfedoseev/django-static-precompiler#84]
My settings:
```
STATIC_URL = 'static/'
STATIC_ROOT = 'static'

STATIC_PRECOMPILER_COMPILERS = (
    ('static_precompiler.compilers.LESS', {
        'sourcemap_enabled': True,
    }),
)
```

```
{% load compile_static %}
{% load static %}

<link rel="stylesheet" href="{% static "less/common/styles.less"|compile %}">
```

Why I get that doubled `\static\`?
`lessc: ENOENT: no such file or directory, open 'C:\htdocs\shopelectro\static\static\less\common\styles.less'`

If I'll change `STATIC_ROOT = 'static'` to `STATIC_ROOT = 'somethingother'`. Then I'll get:
`Can't find staticfile named: less/common/styles.less`

**Comment by YozhEzhi** [comment]
`STATIC_ROOT = os.path.join(BASE_DIR, 'static')` - fixed my problem.

**Comment by andreyfedoseev** [comment]
`STATIC_ROOT ` must be the absolute path to your static files folder, see Django docs: https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-STATIC_ROOT
