### ISSUE TITLE
compilestatic --watch

### ISSUE THREAD

**Issue by mezhopking** [andreyfedoseev/django-static-precompiler#87]
Hi - I'm trying to setup compilestatic --watch. My SCSS source project is obviously built using lots of imports and files, which all compile to a single CSS file. However, when I run the above command 'djang-static-precompiler' tries to outputs every single *.SCSS file in my project separately. This obviously throws lots of errors, due to var inheritance etc etc. 

When using DSP regularly in the templates of my django project, it behaves as expected.

How can I get --watch to output a single CSS file from the master SCSS file?

Thank you

**Comment by andreyfedoseev** [comment]
static-precompiler mimics the default SASS behaviour: files with names starting with and underscore (`_`) are ignored by the compiler. This is the default way to exclude the individual imported files from the compilation process. Let me know if it helps.

See "Partials" section at http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import

**Comment by mezhopking** [comment]
Oh of course! Thanks :)
