### ISSUE TITLE
scss include file paths

### ISSUE THREAD

**Issue by KevinSeghetti** [andreyfedoseev/django-static-precompiler#91]
I seem to be having trouble getting scss includes to work under the precompiler. 

I've tried a variety of relative and absolute paths in load_paths, when seems to change which error I get, but haven't found a combination that works. Seems to be a disconnect in how load_paths is searched between locate_imported_file vs where sass looks based on -I. (maybe a different current working directory?)

Is there a test suite that exercises each precompiler I could look at? (to either learn what I am doing wrong, or to enhance to show the issue I am having). 

I see test_project in the precompiler source on github, but it doesn't seem to do much. 

Thankls

**Comment by KevinSeghetti** [comment]
One issue I just noticed: the scss precompiler module doesn't honor comments when searching for imports. 
the line:
//@import '_colors';

causes a 
Can't locate the imported file: _colors
error to be thrown.

**Comment by andreyfedoseev** [comment]
Regarding the comments, there's an open issue for that https://github.com/andreyfedoseev/django-static-precompiler/issues/81

**Comment by andreyfedoseev** [comment]
@KevinSeghetti the inconsistencies of `load_paths` handling are fixed in cf70f3ba9c82daf430b79712695db8dadf820a5f
