### ISSUE TITLE
Using --watch option

### ISSUE THREAD

**Issue by Jakobovski** [andreyfedoseev/django-static-precompiler#97]
Great library! Thanks

Can you please elaborate on how to use the --watch option? I was unable to figure it out from the documentation.  I will be happy to update the documentation if you can explain it here.

Thanks.

**Comment by andreyfedoseev** [comment]
When you run `./manage compilestatic` with `--watch` option, `static_precompiler` will compile all the files that you have and then keep running to monitor the changes. Once a change is detected it will re-compile the file.

**Comment by andreyfedoseev** [comment]
This option is intended to be used for development only.
